spring:
  application:
    name: orders
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/orders}
    username: ${SPRING_DATASOURCE_USERNAME:orders}
    password: ${SPRING_DATASOURCE_PASSWORD:orders}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
  cloud:
    consul:
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 15s
      config:
        enabled: false
        import-check:
          enabled: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
